### PR TITLE
Initial port to conda builds

### PR DESCRIPTION
**Pull request by 183amir**
@anjos could you give me push access pls?

### CODE REVIEW

**Comment by anjos** [comment]
@183amir. You should be able to accept the pull requests. Please check and confirm.

**Comment by 183amir** [comment]
I can now, thanks.

**Comment by 183amir** [comment]
Andre could you please try the builds on Mac OS again? Preferably a virtual machine.

**Comment by anjos** [comment]
VMs are tough... I can build on my existing base OS for starters.

**Pull request merged**
